use anchor_lang::prelude::*;
use std::mem::size_of;

// The Program ID (This will be generated by your Anchor CLI)
declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");

#[program]
pub mod celestial_spine {
    use super::*;

    /// THE REFLEX ACTION
    /// Executes a trade only if the 'Vortex Geometry' aligns.
    pub fn execute_reflex(ctx: Context<ExecuteReflex>, volatility_index: u64, latency_score: u64) -> Result<()> {
        let interaction = &mut ctx.accounts.interaction_log;
        
        // 1. DEFENSE: On-Chain Risk Check
        // If latency score (0-100) is too high, the blockchain itself rejects the transaction.
        if latency_score > 80 {
            return Err(ErrorCode::SystemUnstable.into());
        }

        // 2. GEOMETRY: The Golden Ratio Multiplier (Scaled by 1000 for integer math)
        // 1.618 * Volatility
        let phi_scalar = 1618; 
        let risk_weight = (volatility_index * phi_scalar) / 1000;

        // 3. IMMUTABLE LOGGING
        interaction.authority = *ctx.accounts.authority.key;
        interaction.timestamp = Clock::get()?.unix_timestamp;
        interaction.risk_weight = risk_weight;
        
        msg!("⚡ SPINE ACTIVATED: Risk Weight calculated at {}", risk_weight);
        
        Ok(())
    }
}

// --- DATA STRUCTURES ---

#[derive(Accounts)]
pub struct ExecuteReflex<'info> {
    #[account(init_if_needed, payer = authority, space = 8 + size_of::<InteractionLog>())]
    pub interaction_log: Account<'info, InteractionLog>,
    #[account(mut)]
    pub authority: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[account]
pub struct InteractionLog {
    pub authority: Pubkey,
    pub timestamp: i64,
    pub risk_weight: u64,
}

#[error_code]
pub enum ErrorCode {
    #[msg("High Latency Detected. Reflex Blocked.")]
    SystemUnstable,
}
